# Generated by Django migration

from django.db import migrations, models
from decimal import Decimal


def create_site_settings(apps, schema_editor):
    """Create the initial SiteSettings instance with default filter_radius of 10.0"""
    SiteSettings = apps.get_model('properties', 'SiteSettings')
    SiteSettings.objects.get_or_create(
        pk=1,
        defaults={'filter_radius': Decimal('10.0')}
    )


def remove_site_settings(apps, schema_editor):
    """Remove the SiteSettings instance"""
    SiteSettings = apps.get_model('properties', 'SiteSettings')
    SiteSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_change_price_to_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_radius', models.DecimalField(decimal_places=2, default=10.0, help_text='Default filter radius in kilometers for latitude/longitude-based property searches', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.RunPython(create_site_settings, remove_site_settings),
    ]

